### ISSUE TITLE
migrate to new file format

### ISSUE THREAD

**Issue by smarcet** [fntechgit/fnevent-tier1-default-theme#2]
here
https://github.com/fntechgit/fnevent-tier1-default-theme/blob/47e4903bf0c9f78c3a711c6905cb04275a8a89d9/src/content/marketing-page/index.json#L33
do we need to perform same migrations as we did here 
https://github.com/fntechgit/fnevent-2024ocpregional-theme/commit/0360ffc0d9f90b033ce53d26fd977adcefb4d4e1?

**Comment by smarcet** [comment]
this is related to https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3475158&stafilter=NotComplete&fileview=grid

**Comment by gcutrini** [comment]
This has been addressed in 507d626f303ac62c1118139894c735c47627a8e0
Closing.
